from PyQt5 import QtCore, QtGui, QtWidgets

from scrolllabel import ScrollLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 521, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.TypeComboBox = QtWidgets.QComboBox(self.tab)
        self.TypeComboBox.setGeometry(QtCore.QRect(50, 10, 451, 24))
        self.TypeComboBox.setObjectName("TypeComboBox")
        self.UrlLine = QtWidgets.QLineEdit(self.tab)
        self.UrlLine.setGeometry(QtCore.QRect(50, 50, 451, 28))
        self.UrlLine.setObjectName("UrlLine")
        self.FormatComboBox = QtWidgets.QComboBox(self.tab)
        self.FormatComboBox.setGeometry(QtCore.QRect(110, 100, 141, 31))
        self.FormatComboBox.setObjectName("FormatComboBox")
        self.Button = QtWidgets.QPushButton(self.tab)
        self.Button.setEnabled(False)
        self.Button.setGeometry(QtCore.QRect(290, 100, 111, 31))
        self.Button.setObjectName("Button")
        self.TypeLabel = QtWidgets.QLabel(self.tab)
        self.TypeLabel.setGeometry(QtCore.QRect(10, 15, 32, 16))
        self.TypeLabel.setObjectName("TypeLabel")
        self.UrlLabel = QtWidgets.QLabel(self.tab)
        self.UrlLabel.setGeometry(QtCore.QRect(10, 55, 58, 16))
        self.UrlLabel.setObjectName("UrlLabel")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(50, 150, 411, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.VideoAuthor = QtWidgets.QLabel(self.frame)
        self.VideoAuthor.setGeometry(QtCore.QRect(30, 30, 211, 21))
        self.VideoAuthor.setText("")
        self.VideoAuthor.setObjectName("VideoAuthor")
        self.VideoTitle = QtWidgets.QLabel(self.frame)
        self.VideoTitle.setGeometry(QtCore.QRect(30, 70, 211, 61))
        self.VideoTitle.setText("")
        self.VideoTitle.setWordWrap(True)
        self.VideoTitle.setObjectName("VideoTitle")
        self.VideoPhoto = QtWidgets.QLabel(self.frame)
        self.VideoPhoto.setGeometry(QtCore.QRect(250, 30, 141, 101))
        self.VideoPhoto.setText("")
        self.VideoPhoto.setScaledContents(True)
        self.VideoPhoto.setObjectName("VideoPhoto")
        self.downloadProgressBar = QtWidgets.QProgressBar(self.frame)
        self.downloadProgressBar.setGeometry(QtCore.QRect(40, 150, 331, 23))
        self.downloadProgressBar.setProperty("value", 0)
        self.downloadProgressBar.setObjectName("downloadProgressBar")
        self.ItemsProgressBar = QtWidgets.QProgressBar(self.frame)
        self.ItemsProgressBar.setGeometry(QtCore.QRect(40, 180, 331, 23))
        self.ItemsProgressBar.setProperty("value", 0)
        self.ItemsProgressBar.setTextVisible(False)
        self.ItemsProgressBar.setObjectName("ItemsProgressBar")
        self.ItemsLabel = QtWidgets.QLabel(self.frame)
        self.ItemsLabel.setGeometry(QtCore.QRect(40, 180, 331, 20))
        self.ItemsLabel.setText("")
        self.ItemsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ItemsLabel.setObjectName("ItemsLabel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.UrlLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.UrlLabel_2.setGeometry(QtCore.QRect(10, 55, 58, 16))
        self.UrlLabel_2.setObjectName("UrlLabel_2")
        self.UrlLine_2 = QtWidgets.QLineEdit(self.tab_2)
        self.UrlLine_2.setGeometry(QtCore.QRect(50, 50, 451, 28))
        self.UrlLine_2.setObjectName("UrlLine_2")
        self.FolderPathLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.FolderPathLabel_2.setGeometry(QtCore.QRect(10, 15, 71, 16))
        self.FolderPathLabel_2.setObjectName("FolderPathLabel_2")
        self.FolderPathLine_2 = QtWidgets.QLineEdit(self.tab_2)
        self.FolderPathLine_2.setGeometry(QtCore.QRect(90, 10, 321, 28))
        self.FolderPathLine_2.setObjectName("FolderPathLine_2")
        self.FolderPathButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.FolderPathButton_2.setGeometry(QtCore.QRect(420, 10, 80, 28))
        self.FolderPathButton_2.setObjectName("FolderPathButton_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(50, 150, 421, 251))
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.InFolderScrollArea = ScrollLabel(self.tab_5)
        self.InFolderScrollArea.setGeometry(QtCore.QRect(0, 0, 421, 221))
        self.InFolderScrollArea.setObjectName("InFolderScrollArea")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.InPlaylistScrollArea = ScrollLabel(self.tab_6)
        self.InPlaylistScrollArea.setGeometry(QtCore.QRect(0, 0, 421, 221))
        self.InPlaylistScrollArea.setObjectName("InPlaylistScrollArea")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.FormatComboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.FormatComboBox_2.setGeometry(QtCore.QRect(50, 100, 141, 31))
        self.FormatComboBox_2.setObjectName("FormatComboBox_2")
        self.AnalyzeButton = QtWidgets.QPushButton(self.tab_2)
        self.AnalyzeButton.setEnabled(False)
        self.AnalyzeButton.setGeometry(QtCore.QRect(220, 100, 111, 31))
        self.AnalyzeButton.setObjectName("AnalyzeButton")
        self.UpdateButton = QtWidgets.QPushButton(self.tab_2)
        self.UpdateButton.setEnabled(False)
        self.UpdateButton.setGeometry(QtCore.QRect(360, 100, 111, 31))
        self.UpdateButton.setObjectName("UpdateButton")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download Tube"))
        self.Button.setText(_translate("MainWindow", "Download"))
        self.TypeLabel.setText(_translate("MainWindow", "Type:"))
        self.UrlLabel.setText(_translate("MainWindow", "URL:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Initial Download"))
        self.UrlLabel_2.setText(_translate("MainWindow", "URL:"))
        self.FolderPathLabel_2.setText(_translate("MainWindow", "Folder Path:"))
        self.FolderPathButton_2.setText(_translate("MainWindow", "Browse"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Only in folder"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Only in playlist"))
        self.AnalyzeButton.setText(_translate("MainWindow", "Analyze"))
        self.UpdateButton.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Update playlist"))

